/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ActionDef, CharacterState } from '../types/game';

// Базовые начальные параметры MORVAN
export const INITIAL_MORVAN: CharacterState = {
  id: 'morvan',
  name: 'MORVAN',
  title: 'Северный берсерк с боевым топором',
  hp: 100,
  maxHp: 100,
  isBlocking: false,
  isDodging: false,
  status: 'idle',
  ultimateCharge: 30, // Начинает с частичным зарядом
};

// Базовые начальные параметры ELYRA
export const INITIAL_ELYRA: CharacterState = {
  id: 'elyra',
  name: 'ELYRA',
  title: 'Готическая колдунья Бездны',
  hp: 100,
  maxHp: 100,
  isBlocking: false,
  isDodging: false,
  status: 'idle',
  ultimateCharge: 30,
};

// Действия игрока MORVAN (Ближний бой, топор, физическая мощь)
export const MORVAN_ACTIONS: ActionDef[] = [
  {
    id: 'light_attack',
    name: 'Удар топором',
    shortName: 'Удар [1]',
    description: 'Быстрый рубящий выпад топором. Эффективен вблизи и на средней дистанции.',
    minDamage: 14,
    maxDamage: 20,
    requiredDistance: ['close', 'mid'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '1',
  },
  {
    id: 'heavy_attack',
    name: 'Сокрушающий разруб',
    shortName: 'Тяжелый удар [2]',
    description: 'Мощный размах двумя руками. Вызывает сотрясение арены и наносит огромный урон. Доступен вблизи.',
    minDamage: 26,
    maxDamage: 36,
    requiredDistance: ['close'],
    cooldownTurns: 2,
    currentCooldown: 0,
    keyboardKey: '2',
  },
  {
    id: 'approach',
    name: 'Рывок вперед',
    shortName: 'Сближение [3]',
    description: 'Быстро сокращает дистанцию до соперника (Дальняя → Средняя → Близкая).',
    minDamage: 0,
    maxDamage: 0,
    requiredDistance: ['mid', 'far'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '3',
    isMovement: true,
  },
  {
    id: 'retreat',
    name: 'Отскок назад',
    shortName: 'Отход [4]',
    description: 'Увеличивает дистанцию, разрывая ближний бой (Близкая → Средняя → Дальняя).',
    minDamage: 0,
    maxDamage: 0,
    requiredDistance: ['close', 'mid'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '4',
    isMovement: true,
  },
  {
    id: 'block',
    name: 'Защитная стойка',
    shortName: 'Блок [5]',
    description: 'Прикрыться рукоятью топора и наплечником. Снижает урон от следующей атаки на 75%.',
    minDamage: 0,
    maxDamage: 0,
    cooldownTurns: 1,
    currentCooldown: 0,
    keyboardKey: '5',
    isDefense: true,
  },
  {
    id: 'dodge',
    name: 'Боковой перекат',
    shortName: 'Уклонение [6]',
    description: 'Ловкий маневр. Полностью избегает урона от входящего удара с высокой вероятностью.',
    minDamage: 0,
    maxDamage: 0,
    cooldownTurns: 2,
    currentCooldown: 0,
    keyboardKey: '6',
    isDefense: true,
  },
  {
    id: 'ultimate',
    name: 'Ярость Валгалы',
    shortName: 'УЛЬТИМЕЙТ [R]',
    description: 'Сокрушительный прыжок с рассекающей огненной волной. Требует 100% ярости.',
    minDamage: 40,
    maxDamage: 52,
    cooldownTurns: 4,
    currentCooldown: 0,
    keyboardKey: 'r',
    isUltimate: true,
  },
];

// Действия бота ELYRA (Магия, посох, дальний бой, телепортация)
export const ELYRA_ACTIONS: ActionDef[] = [
  {
    id: 'magic_projectile',
    name: 'Сфера Бездны',
    shortName: 'Снаряд',
    description: 'Дальний сгусток фиолетовой энергии, летящий через всю арену.',
    minDamage: 13,
    maxDamage: 19,
    requiredDistance: ['mid', 'far'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '',
    isRanged: true,
  },
  {
    id: 'heavy_attack',
    name: 'Взрыв темной материи',
    shortName: 'Сильная магия',
    description: 'Концентрированная вспышка из навершия посоха с разрушительной силой.',
    minDamage: 25,
    maxDamage: 34,
    requiredDistance: ['close', 'mid'],
    cooldownTurns: 2,
    currentCooldown: 0,
    keyboardKey: '',
  },
  {
    id: 'light_attack',
    name: 'Удар посохом',
    shortName: 'Удар посохом',
    description: 'Быстрый тычок зачарованным кристаллом посоха вблизи.',
    minDamage: 10,
    maxDamage: 15,
    requiredDistance: ['close'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '',
  },
  {
    id: 'approach',
    name: 'Шаг сквозь туман',
    shortName: 'Сближение',
    description: 'Приближается к игроку для более точной атаки.',
    minDamage: 0,
    maxDamage: 0,
    requiredDistance: ['mid', 'far'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '',
    isMovement: true,
  },
  {
    id: 'retreat',
    name: 'Мерцающий отскок',
    shortName: 'Отход',
    description: 'Увеличивает дистанцию, спасаясь от сокрушительного топора.',
    minDamage: 0,
    maxDamage: 0,
    requiredDistance: ['close', 'mid'],
    cooldownTurns: 0,
    currentCooldown: 0,
    keyboardKey: '',
    isMovement: true,
  },
  {
    id: 'block',
    name: 'Астральный щит',
    shortName: 'Барьер',
    description: 'Окружает себя мерцающим фиолетовым барьером, поглощая 75% урона.',
    minDamage: 0,
    maxDamage: 0,
    cooldownTurns: 1,
    currentCooldown: 0,
    keyboardKey: '',
    isDefense: true,
  },
  {
    id: 'dodge',
    name: 'Теневой фазовый сдвиг',
    shortName: 'Уклонение',
    description: 'Растворяется в воздухе на мгновение, полностью избегая удара.',
    minDamage: 0,
    maxDamage: 0,
    cooldownTurns: 2,
    currentCooldown: 0,
    keyboardKey: '',
    isDefense: true,
  },
  {
    id: 'ultimate',
    name: 'Астральный катаклизм',
    shortName: 'УЛЬТИМЕЙТ',
    description: 'Космический метеоритный шквал, наносящий колоссальный магический урон.',
    minDamage: 38,
    maxDamage: 50,
    cooldownTurns: 4,
    currentCooldown: 0,
    keyboardKey: '',
    isUltimate: true,
  },
];
